/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hoangnguyen.dev.App;

import hoangnguyen.dev.Protocol.ImapClient;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Frm_Trash extends javax.swing.JFrame {

    private ImapClient imapClient;
    private DefaultListModel<String> listModel;
    private String imapHost;
    private int imapPort;
    private String userEmail;
    private String password;
    private List<Email> emails;
    /**
     * Creates new form frmHome
     */
    public Frm_Trash() {
        initComponents();
    }

    public Frm_Trash(String imapHost, int imapPort, String userEmail, String password) {
        this.userEmail = userEmail;
        this.password = password;
        this.imapHost = imapHost;
        this.imapPort = imapPort;
        initComponents();
        setupImapClient();
    }
    
    private void setupImapClient() {
        imapClient = new ImapClient();
        listModel = new DefaultListModel<>(); // Khởi tạo mô hình danh sách
        listTrash.setModel(listModel); // Gán mô hình vào JList

        try {
            imapClient.connect(imapHost, imapPort); // Kết nối với server IMAP
            if (imapClient.login(userEmail, password)) {
                List<String> folders = imapClient.listFolders(); // Lấy danh sách thư mục
                for (String folder : folders) {
                    System.out.println(folder); // In ra danh sách thư mục
                }

                // Chọn thư mục "INBOX"
                if (imapClient.selectFolder("[Gmail]/Th&APk-ng r&AOE-c")) { // Chọn "INBOX" thay vì "[Gmail]/INBOX"
                    emails = imapClient.listEmails(); // Lấy danh sách email
                    for (Email email : emails) {
                        listModel.addElement(email.getSubject()); // Thêm tiêu đề email vào mô hình
                    }
                } else {
                    System.out.println("Failed to select folder");
                }
            } else {
                System.out.println("Login failed");
            }
        } catch (IOException ex) {
            ex.printStackTrace(); // Xử lý lỗi
        }
    }

    
    private void displayEmailDetails(int index) {
        Email email = emails.get(index);
        lb_subject.setText(email.getSubject());
        txt_sender.setText(email.getDecodedSender());  
        txt_date.setText(email.getDate());
        txt_receiver.setText(email.getDecodedRecipient()); 
        txt_message.setText(email.getBody());

         if(email.isHasAttachment()){
            txt_attachmentFile.setText(email.getAttachmentName());
            btn_attachment.setEnabled(true);
        }
        else{
            txt_attachmentFile.setText("No attachment");
            btn_attachment.setEnabled(false);
                    
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTrash = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        lb_subject = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_sender = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_receiver = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_message = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txt_attachmentFile = new javax.swing.JTextField();
        btn_attachment = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnMovetoReceived = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btn_home = new javax.swing.JMenu();
        jmenu_exit = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("TRASH");

        listTrash.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTrash.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTrashValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listTrash);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lb_subject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_subject.setText("Subject");

        jLabel1.setText("Sender:");

        txt_sender.setEnabled(false);

        jLabel4.setText("Receiver:");

        txt_receiver.setEnabled(false);

        jLabel3.setText("Date:");

        txt_date.setEnabled(false);

        txt_message.setColumns(20);
        txt_message.setRows(5);
        txt_message.setEnabled(false);
        jScrollPane2.setViewportView(txt_message);

        jLabel5.setText("Attached file:");

        txt_attachmentFile.setText("No attachment");
        txt_attachmentFile.setEnabled(false);

        btn_attachment.setText("Save As");
        btn_attachment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attachmentActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnMovetoReceived.setText("Move to Received");
        btnMovetoReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovetoReceivedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lb_subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMovetoReceived))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                            .addComponent(txt_sender)
                            .addComponent(txt_receiver)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_attachmentFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_attachment)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_subject)
                    .addComponent(btnDelete)
                    .addComponent(btnMovetoReceived))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_sender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_receiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_attachmentFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_attachment)
                    .addComponent(jLabel5))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        jmenu_exit.setText("Exit");
        jmenu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_exitActionPerformed(evt);
            }
        });
        btn_home.add(jmenu_exit);

        jMenuBar1.add(btn_home);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        
    }//GEN-LAST:event_btn_homeActionPerformed

    private void jmenu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_exitActionPerformed
        Frm_Home frm_Home = new Frm_Home(userEmail,password);
        frm_Home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmenu_exitActionPerformed

    
    private void listTrashValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTrashValueChanged
        if(!evt.getValueIsAdjusting()){
            int selectedIndex = listTrash.getSelectedIndex();
            if(selectedIndex != -1){
                displayEmailDetails(selectedIndex);
            }
        }
    }//GEN-LAST:event_listTrashValueChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedIndex = listTrash.getSelectedIndex();
        if (selectedIndex != -1) {
        Email emailToDelete = emails.get(selectedIndex);
        try {
            imapClient.deleteEmail(emailToDelete.getId());
            listModel.remove(selectedIndex);
            emails.remove(selectedIndex);
             // Xóa nội dung chi tiết email đã xóa
                lb_subject.setText(""); 
                txt_receiver.setText("");
                txt_date.setText("");
                txt_sender.setText("");
                txt_message.setText("");
                txt_attachmentFile.setText("");
            JOptionPane.showMessageDialog(this, "Email received deleted successfully!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to delete received email.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "No received email selected.");
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnMovetoReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovetoReceivedActionPerformed
     int selectedIndex = listTrash.getSelectedIndex();
        if (selectedIndex != -1) {
            Email emailToMove = emails.get(selectedIndex);
            try {
                // Di chuyển email về hộp thư đến
                boolean success = imapClient.moveToInbox(emailToMove.getId());
                if (success) {
                    listModel.remove(selectedIndex); // Cập nhật danh sách hiển thị
                    emails.remove(selectedIndex); // Cập nhật danh sách emails
                    // Xóa nội dung chi tiết email đã xóa
                    lb_subject.setText(""); 
                    txt_receiver.setText("");
                    txt_date.setText("");
                    txt_sender.setText("");
                    txt_message.setText("");
                    txt_attachmentFile.setText("");
                    JOptionPane.showMessageDialog(this, "Email has been migrated successfully.");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to move email. Please try again.");
                }
            } catch (Exception e) {
                e.printStackTrace(); // Xử lý lỗi nếu có
                JOptionPane.showMessageDialog(this, "An error occurred while moving the email.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No email selected in Trash.");
        }
    }//GEN-LAST:event_btnMovetoReceivedActionPerformed

    private void btn_attachmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attachmentActionPerformed
        int selectedIndex = listTrash.getSelectedIndex();
        if(selectedIndex != -1){
            Email email = emails.get(selectedIndex);
            if(email.isHasAttachment()){
                try{
                    byte[] attachmentData = imapClient.downloadAttachment(email.getId(), email.getAttachmentName());
                    saveAndOpenAttachment(attachmentData, email.getAttachmentName());
                }
                catch(IOException ex){
                    JOptionPane.showMessageDialog(this, "Error downloading attachment: " + ex.getMessage(), "Download Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_attachmentActionPerformed

    private void saveAndOpenAttachment(byte[] attachmentData, String fileName) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Attachment");
        fileChooser.setSelectedFile(new File(fileName)); // Đặt tên file mặc định
    
        // Hiển thị hộp thoại lưu file
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            try (FileOutputStream fos = new FileOutputStream(fileToSave)) {
                fos.write(attachmentData);
                // Mở file sau khi lưu
                Desktop.getDesktop().open(fileToSave);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error saving or opening attachment: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeeltxt_recipientNamevax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frm_ListMailReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frm_ListMailReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frm_ListMailReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frm_ListMailReceive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Trash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMovetoReceived;
    private javax.swing.JButton btn_attachment;
    private javax.swing.JMenu btn_home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jmenu_exit;
    private javax.swing.JLabel lb_subject;
    private javax.swing.JList<String> listTrash;
    private javax.swing.JTextField txt_attachmentFile;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextArea txt_message;
    private javax.swing.JTextField txt_receiver;
    private javax.swing.JTextField txt_sender;
    // End of variables declaration//GEN-END:variables
}
